"""Exam question bank — id, topic, type, question."""

exam_questions = [
    {'id': 1, 'topic': 'Home', 'type': 'Description', 'question': "Can you tell me about your home? What's the layout like and how many rooms do you have?"},
    {'id': 2, 'topic': 'Home', 'type': 'Description', 'question': 'What kinds of things do people usually take care of in your home? Who does what?'},
    {'id': 3, 'topic': 'Home', 'type': 'Description', 'question': "Which room do you spend the most time in at home? What's it like?"},
    {'id': 4, 'topic': 'Home', 'type': 'Description', 'question': 'Walk me through your home — what does it look like inside and outside?'},
    {'id': 5, 'topic': 'Movies', 'type': 'Description', 'question': 'What kinds of movies are you into these days?'},
    {'id': 6, 'topic': 'Shows', 'type': 'Description', 'question': 'What kinds of performances or shows do you enjoy watching?'},
    {'id': 7, 'topic': 'Park', 'type': 'Description', 'question': "Is there a park you really like going to? What's special about it?"},
    {'id': 8, 'topic': 'Beach', 'type': 'Description', 'question': 'Tell me about your favorite beach. What does it look like?'},
    {'id': 9, 'topic': 'Coffee', 'type': 'Description', 'question': "Is there a coffee shop you go to often? Tell me what it's like and where it is."},
    {'id': 10, 'topic': 'Shopping', 'type': 'Description', 'question': 'Do you enjoy shopping? Tell me where you usually go and who you like shopping with.'},
    {'id': 11, 'topic': 'Shows', 'type': 'Description', 'question': 'What TV shows or movies do you enjoy watching the most? Why do you like them?'},
    {'id': 12, 'topic': 'Music', 'type': 'Description', 'question': 'What kind of music do you usually listen to?'},
    {'id': 13, 'topic': 'Music', 'type': 'Description', 'question': 'What kinds of songs do you enjoy singing?'},
    {'id': 14, 'topic': 'Instrument', 'type': 'Description', 'question': 'Do you play any musical instruments? What kind of music do you like playing?'},
    {'id': 15, 'topic': 'Cooking', 'type': 'Description', 'question': 'What do you usually like cooking? Why do you enjoy making those dishes?'},
    {'id': 16, 'topic': 'Books', 'type': 'Description', 'question': 'What kinds of books do you enjoy reading?'},
    {'id': 17, 'topic': 'Walking', 'type': 'Description', 'question': "Where do you usually go for a walk? What's the area like?"},
    {'id': 18, 'topic': 'Exercise', 'type': 'Description', 'question': 'Where do you usually go jogging? Describe the place for me.'},
    {'id': 19, 'topic': 'Exercise', 'type': 'Description', 'question': "Tell me about the gym or fitness center you go to. What's it like?"},
    {'id': 20, 'topic': 'Travel', 'type': 'Description', 'question': 'What places do you enjoy traveling to? Why do you like them?'},
    {'id': 21, 'topic': 'Travel', 'type': 'Description', 'question': 'Tell me about a city or country you visited on vacation. What stood out to you?'},
    {'id': 22, 'topic': 'Travel', 'type': 'Description', 'question': 'Who do you usually spend time with on vacation?'},
    {'id': 23, 'topic': 'Home', 'type': 'Description', 'question': "Tell me about the area where you live. What's the atmosphere like?"},
    {'id': 24, 'topic': 'Home', 'type': 'Description', 'question': 'What kind of furniture do you have at home? Do you have a favorite piece?'},
    {'id': 25, 'topic': 'Country', 'type': 'Description', 'question': 'What are some important holidays in your country?'},
    {'id': 26, 'topic': 'Country', 'type': 'Description', 'question': 'How does recycling usually work in your country?'},
    {'id': 27, 'topic': 'Country', 'type': 'Description', 'question': "What's the geography like in your country? Are there mountains or beaches?"},
    {'id': 28, 'topic': 'Country', 'type': 'Description', 'question': 'When you need time off from work, what do you usually do?'},
    {'id': 29, 'topic': 'Country', 'type': 'Description', 'question': 'What kinds of gatherings or celebrations are common in your country?'},
    {'id': 30, 'topic': 'Country', 'type': 'Description', 'question': 'What are hotels in your country usually like?'},
    {'id': 31, 'topic': 'Country', 'type': 'Description', 'question': 'What kinds of technology do people use a lot these days in your country?'},
    {'id': 32, 'topic': 'Phones', 'type': 'Description', 'question': 'Tell me about your phone. What do you mainly use it for?'},
    {'id': 33, 'topic': 'Internet', 'type': 'Description', 'question': 'What do people usually do online these days?'},
    {'id': 34, 'topic': 'Country', 'type': 'Description', 'question': 'What are some major industries or companies in your country?'},
    {'id': 35, 'topic': 'Country', 'type': 'Description', 'question': 'How do people usually get around in your country?'},
    {'id': 36, 'topic': 'Restaurant', 'type': 'Description', 'question': 'Tell me about your favorite restaurant. Why do you like it so much?'},
    {'id': 37, 'topic': 'Food', 'type': 'Description', 'question': 'What are some traditional foods in your country?'},
    {'id': 38, 'topic': 'Health', 'type': 'Description', 'question': 'What does being healthy mean to you?'},
    {'id': 39, 'topic': 'Money', 'type': 'Description', 'question': 'What are banks in your country usually like?'},
    {'id': 40, 'topic': 'Health', 'type': 'Description', 'question': 'What kinds of appointments do you usually make?'},
    {'id': 41, 'topic': 'Country', 'type': 'Description', 'question': "What's the weather like in your country throughout the year?"},
    {'id': 42, 'topic': 'Fashion', 'type': 'Description', 'question': 'What kinds of clothes do people usually wear in your country?'},
    {'id': 43, 'topic': 'Home', 'type': 'Routine', 'question': "What's your usual routine like at home during the week and on weekends?"},
    {'id': 44, 'topic': 'Home', 'type': 'Routine', 'question': 'How do you usually handle your responsibilities at home?'},
    {'id': 45, 'topic': 'Home', 'type': 'Routine', 'question': 'What do you usually do with your family at home?'},
    {'id': 46, 'topic': 'Home', 'type': 'Routine', 'question': 'Tell me about a normal day at home for you.'},
    {'id': 47, 'topic': 'Home', 'type': 'Routine', 'question': 'What kinds of chores do you usually do around the house?'},
    {'id': 48, 'topic': 'Movies', 'type': 'Routine', 'question': 'When you go see a movie, what do you usually do before and after?'},
    {'id': 49, 'topic': 'Shows', 'type': 'Routine', 'question': 'What do you usually do when you go watch a play or musical?'},
    {'id': 50, 'topic': 'Park', 'type': 'Routine', 'question': 'What do you normally do when you visit a park?'},
    {'id': 51, 'topic': 'Beach', 'type': 'Routine', 'question': "What's a typical beach day like for you?"},
    {'id': 52, 'topic': 'Sports', 'type': 'Routine', 'question': 'What sports do you enjoy watching on TV?'},
    {'id': 53, 'topic': 'Coffee', 'type': 'Routine', 'question': 'What do you usually do at a coffee shop?'},
    {'id': 54, 'topic': 'Shopping', 'type': 'Routine', 'question': 'Walk me through a typical shopping day.'},
    {'id': 55, 'topic': 'Shows', 'type': 'Routine', 'question': "Who's your favorite movie or TV character? What do you like about them?"},
    {'id': 56, 'topic': 'Music', 'type': 'Routine', 'question': 'When do you usually listen to music?'},
    {'id': 57, 'topic': 'Music', 'type': 'Routine', 'question': 'Do you sing often? When do you usually sing?'},
    {'id': 58, 'topic': 'Instrument', 'type': 'Routine', 'question': 'Tell me about your routine when you practice your instrument.'},
    {'id': 59, 'topic': 'Cooking', 'type': 'Routine', 'question': 'Can you walk me through how you usually cook a meal?'},
    {'id': 60, 'topic': 'Books', 'type': 'Routine', 'question': 'Tell me about your reading habits.'},
    {'id': 61, 'topic': 'Walking', 'type': 'Routine', 'question': "How often do you go for walks? What's your routine like?"},
    {'id': 62, 'topic': 'Exercise', 'type': 'Routine', 'question': 'What do you usually do before and while jogging?'},
    {'id': 63, 'topic': 'Exercise', 'type': 'Routine', 'question': "What's your usual routine at the gym?"},
    {'id': 64, 'topic': 'Travel', 'type': 'Routine', 'question': 'What do you usually do to prepare for a trip?'},
    {'id': 65, 'topic': 'Travel', 'type': 'Routine', 'question': 'What kinds of things do you enjoy doing while traveling abroad?'},
    {'id': 66, 'topic': 'Travel', 'type': 'Routine', 'question': 'What activities do you usually do with people during vacations?'},
    {'id': 67, 'topic': 'Country', 'type': 'Routine', 'question': "What's your neighborhood usually like during the day?"},
    {'id': 68, 'topic': 'Home', 'type': 'Routine', 'question': 'How do you normally use the furniture in your home?'},
    {'id': 69, 'topic': 'Country', 'type': 'Routine', 'question': 'Tell me about one important holiday in your country.'},
    {'id': 70, 'topic': 'Country', 'type': 'Routine', 'question': 'Walk me through how you usually recycle things.'},
    {'id': 71, 'topic': 'Country', 'type': 'Routine', 'question': 'What kinds of outdoor activities are popular in your country?'},
    {'id': 72, 'topic': 'Country', 'type': 'Routine', 'question': 'What do people usually do in their free time in Korea?'},
    {'id': 73, 'topic': 'Country', 'type': 'Routine', 'question': 'Tell me about a celebration people prepare a lot for in your country.'},
    {'id': 74, 'topic': 'Country', 'type': 'Routine', 'question': "What's your usual experience like when staying at a hotel?"},
    {'id': 75, 'topic': 'Country', 'type': 'Routine', 'question': 'How does technology help you in your daily life?'},
    {'id': 76, 'topic': 'Phones', 'type': 'Routine', 'question': 'Tell me about your phone call habits.'},
    {'id': 77, 'topic': 'Internet', 'type': 'Routine', 'question': 'What websites or apps do you use the most online?'},
    {'id': 78, 'topic': 'Country', 'type': 'Routine', 'question': 'Tell me about a famous company in your country.'},
    {'id': 79, 'topic': 'Country', 'type': 'Routine', 'question': 'What transportation do you usually use during the week?'},
    {'id': 80, 'topic': 'Restaurant', 'type': 'Routine', 'question': 'Tell me about a typical visit to your favorite restaurant.'},
    {'id': 81, 'topic': 'Food', 'type': 'Routine', 'question': 'What are mealtimes usually like in your country?'},
    {'id': 82, 'topic': 'Health', 'type': 'Routine', 'question': 'Besides food, how do people stay healthy?'},
    {'id': 83, 'topic': 'Money', 'type': 'Routine', 'question': 'What kinds of things do people usually do at banks?'},
    {'id': 84, 'topic': 'Country', 'type': 'Routine', 'question': 'What do you usually do when making an appointment?'},
    {'id': 85, 'topic': 'Fashion', 'type': 'Routine', 'question': "What's your favorite season? What do you usually do then?"},
    {'id': 86, 'topic': 'Fashion', 'type': 'Routine', 'question': 'What are you wearing today? What kind of clothes do you usually like wearing?'},
    {'id': 87, 'topic': 'Home', 'type': 'Initiation', 'question': 'Have you ever had a problem at home, like something breaking or needing repair? Tell me what happened.'},
    {'id': 88, 'topic': 'Home', 'type': 'Initiation', 'question': 'What kinds of responsibilities did you have at home when you were a kid?'},
    {'id': 89, 'topic': 'Home', 'type': 'Initiation', 'question': 'Tell me about the house you grew up in. How is it different now?'},
    {'id': 90, 'topic': 'Home', 'type': 'Initiation', 'question': 'Have you ever had conflicts or problems at home? How did you deal with them?'},
    {'id': 91, 'topic': 'Home', 'type': 'Initiation', 'question': 'What was your old house like when you were younger? How is it different from where you live now?'},
    {'id': 92, 'topic': 'Movies', 'type': 'Initiation', 'question': 'Tell me about the last movie you watched. What did you do that day before and after the movie?'},
    {'id': 93, 'topic': 'Shows', 'type': 'Initiation', 'question': 'How did you first get interested in theater or live performances?'},
    {'id': 94, 'topic': 'Park', 'type': 'Initiation', 'question': 'Tell me about the last time you went to a park. Who did you go with and what did you do there?'},
    {'id': 95, 'topic': 'Beach', 'type': 'Initiation', 'question': 'Tell me about the last time you went to the beach.'},
    {'id': 96, 'topic': 'Sports', 'type': 'Initiation', 'question': 'What was the last sports game you watched on TV? Tell me about it.'},
    {'id': 97, 'topic': 'Coffee', 'type': 'Initiation', 'question': 'Tell me about the first time you went to your favorite coffee shop.'},
    {'id': 98, 'topic': 'Shopping', 'type': 'Initiation', 'question': 'Tell me about a memorable shopping experience you had.'},
    {'id': 99, 'topic': 'Shows', 'type': 'Initiation', 'question': 'How did you first become interested in movies or TV shows?'},
    {'id': 100, 'topic': 'Music', 'type': 'Initiation', 'question': 'When did you first get into music? How has your taste changed over time?'},
    {'id': 101, 'topic': 'Music', 'type': 'Initiation', 'question': 'How did you become interested in singing?'},
    {'id': 102, 'topic': 'Instrument', 'type': 'Initiation', 'question': 'How did you first start playing your instrument?'},
    {'id': 103, 'topic': 'Cooking', 'type': 'Initiation', 'question': 'Tell me about a special meal you cooked recently.'},
    {'id': 104, 'topic': 'Books', 'type': 'Initiation', 'question': 'How did you become interested in reading?'},
    {'id': 105, 'topic': 'Walking', 'type': 'Initiation', 'question': 'When did you start walking regularly? Why?'},
    {'id': 106, 'topic': 'Exercise', 'type': 'Initiation', 'question': 'How did you first get into jogging?'},
    {'id': 107, 'topic': 'Exercise', 'type': 'Initiation', 'question': 'What made you start working out or going to the gym?'},
    {'id': 108, 'topic': 'Travel', 'type': 'Initiation', 'question': 'Tell me about trips you took when you were younger.'},
    {'id': 109, 'topic': 'Travel', 'type': 'Initiation', 'question': 'Tell me about your first trip abroad.'},
    {'id': 110, 'topic': 'Travel', 'type': 'Initiation', 'question': 'Tell me about the last staycation or vacation you spent at home.'},
    {'id': 111, 'topic': 'Country', 'type': 'Initiation', 'question': 'Tell me about the last interaction you had with one of your neighbors.'},
    {'id': 112, 'topic': 'Home', 'type': 'Initiation', 'question': 'What kind of furniture did you have growing up?'},
    {'id': 113, 'topic': 'Country', 'type': 'Initiation', 'question': 'Tell me about a holiday memory from your childhood.'},
    {'id': 114, 'topic': 'Country', 'type': 'Initiation', 'question': 'Have you ever had an interesting or memorable experience while recycling?'},
    {'id': 115, 'topic': 'Country', 'type': 'Initiation', 'question': 'Tell me about a memorable experience you had at a famous place in your country.'},
    {'id': 116, 'topic': 'Country', 'type': 'Initiation', 'question': 'What did you do the last time you had free time?'},
    {'id': 117, 'topic': 'Country', 'type': 'Initiation', 'question': 'Tell me about the last gathering or celebration you attended.'},
    {'id': 118, 'topic': 'Country', 'type': 'Initiation', 'question': 'Tell me about the last time you stayed at a hotel.'},
    {'id': 119, 'topic': 'Country', 'type': 'Initiation', 'question': 'Tell me about a piece of technology that left a strong impression on you.'},
    {'id': 120, 'topic': 'Phones', 'type': 'Initiation', 'question': 'When did talking on the phone become important in your life?'},
    {'id': 121, 'topic': 'Internet', 'type': 'Initiation', 'question': 'Tell me about the first time you used the Internet.'},
    {'id': 122, 'topic': 'Country', 'type': 'Initiation', 'question': "Tell me about challenges you've seen in a company or industry."},
    {'id': 123, 'topic': 'Country', 'type': 'Initiation', 'question': 'Tell me about the last time you used unusual transportation.'},
    {'id': 124, 'topic': 'Restaurant', 'type': 'Initiation', 'question': 'Tell me about a really memorable restaurant experience.'},
    {'id': 125, 'topic': 'Food', 'type': 'Initiation', 'question': 'Describe a memorable meal you had recently.'},
    {'id': 126, 'topic': 'Health', 'type': 'Initiation', 'question': 'Tell me about someone healthy who impressed you.'},
    {'id': 127, 'topic': 'Money', 'type': 'Initiation', 'question': 'Tell me about your last experience at a bank.'},
    {'id': 128, 'topic': 'Health', 'type': 'Initiation', 'question': 'Tell me about the last appointment you had.'},
    {'id': 129, 'topic': 'Fashion', 'type': 'Initiation', 'question': 'Tell me about a memorable experience related to weather.'},
    {'id': 130, 'topic': 'Fashion', 'type': 'Initiation', 'question': 'Tell me about a time you dressed up for a special event.'},
    {'id': 131, 'topic': 'Home', 'type': 'Memorable', 'question': 'Tell me about a problem you had at home and how you solved it.'},
    {'id': 132, 'topic': 'Home', 'type': 'Memorable', 'question': 'Tell me about a time as a kid when you forgot or refused to do something you were supposed to do.'},
    {'id': 133, 'topic': 'Home', 'type': 'Memorable', 'question': 'Tell me about a memorable moment you had with your family at home.'},
    {'id': 134, 'topic': 'Home', 'type': 'Memorable', 'question': 'Describe a challenge you faced at home and how you handled it.'},
    {'id': 135, 'topic': 'Home', 'type': 'Memorable', 'question': 'What was your house like when you first moved in? What changed afterward?'},
    {'id': 136, 'topic': 'Shows', 'type': 'Memorable', 'question': "Who's your favorite actor or actress? Tell me about a memorable news story involving them."},
    {'id': 137, 'topic': 'Park', 'type': 'Memorable', 'question': 'Tell me about an unforgettable experience you had at a park.'},
    {'id': 138, 'topic': 'Beach', 'type': 'Memorable', 'question': 'Tell me about a memorable experience you had at the beach.'},
    {'id': 139, 'topic': 'Sports', 'type': 'Memorable', 'question': 'Tell me about a time when it was difficult to watch a sports game you really wanted to see.'},
    {'id': 140, 'topic': 'Coffee', 'type': 'Memorable', 'question': 'Tell me about a memorable or surprising experience you had at a coffee shop.'},
    {'id': 141, 'topic': 'Shopping', 'type': 'Memorable', 'question': 'Tell me about a shopping experience you still remember clearly.'},
    {'id': 142, 'topic': 'Shows', 'type': 'Memorable', 'question': 'Tell me about a movie or TV show that really stayed with you.'},
    {'id': 143, 'topic': 'Music', 'type': 'Memorable', 'question': 'Tell me about a memorable live music performance you attended.'},
    {'id': 144, 'topic': 'Music', 'type': 'Memorable', 'question': 'Tell me about a memorable experience involving singing.'},
    {'id': 145, 'topic': 'Instrument', 'type': 'Memorable', 'question': 'Tell me about a memorable experience playing an instrument.'},
    {'id': 146, 'topic': 'Cooking', 'type': 'Memorable', 'question': "Tell me about a time your cooking didn't go as planned."},
    {'id': 147, 'topic': 'Books', 'type': 'Memorable', 'question': 'Tell me about a book or piece of writing that really impressed you.'},
    {'id': 148, 'topic': 'Walking', 'type': 'Memorable', 'question': 'Tell me about a memorable walk you had.'},
    {'id': 149, 'topic': 'Exercise', 'type': 'Memorable', 'question': 'Tell me about a memorable jogging experience.'},
    {'id': 150, 'topic': 'Exercise', 'type': 'Memorable', 'question': 'Tell me about a memorable experience you had at the gym.'},
    {'id': 151, 'topic': 'Travel', 'type': 'Memorable', 'question': 'Tell me about something unexpected that happened during a trip.'},
    {'id': 152, 'topic': 'Travel', 'type': 'Memorable', 'question': 'Tell me about an unusual or unforgettable experience you had while on vacation.'},
    {'id': 153, 'topic': 'Country', 'type': 'Memorable', 'question': 'Tell me about a memorable event that happened in your neighborhood.'},
    {'id': 154, 'topic': 'Home', 'type': 'Memorable', 'question': 'Tell me about a time furniture at home got damaged or broken.'},
    {'id': 155, 'topic': 'Country', 'type': 'Memorable', 'question': 'Tell me about a time technology stopped working and caused problems.'},
    {'id': 156, 'topic': 'Phones', 'type': 'Memorable', 'question': 'Tell me about a problem you had with your phone.'},
    {'id': 157, 'topic': 'Internet', 'type': 'Memorable', 'question': 'Tell me about a project where you used the Internet for research.'},
    {'id': 158, 'topic': 'Country', 'type': 'Memorable', 'question': 'Tell me about a transportation problem you experienced.'},
    {'id': 159, 'topic': 'Bundle01', 'type': 'Roleplay_Request', 'question': 'Apt furniture feels wrong for the new layout—at the store with Ava, say what you need and ask 3–4 practical questions before buying.'},
    {'id': 160, 'topic': 'Bundle01', 'type': 'Roleplay_Problem', 'question': 'The furniture you bought has an issue—call the store, explain it clearly, and suggest a couple of fixes.'},
    {'id': 161, 'topic': 'Bundle01', 'type': 'Related_Experience', 'question': 'Have you ever had a problem with something you bought for your home? Tell me what happened and how you dealt with it.'},
    {'id': 162, 'topic': 'Bundle02', 'type': 'Roleplay_Request', 'question': 'Another family may come for lunch next week—check in with people at home and ask a few questions to lock the best day and time.'},
    {'id': 163, 'topic': 'Bundle02', 'type': 'Roleplay_Problem', 'question': 'Lunch with your friend’s family is today, but someone at home is sick—leave a voicemail, explain briefly, and offer other times.'},
    {'id': 164, 'topic': 'Bundle02', 'type': 'Related_Experience', 'question': 'Have you ever had to change your plans because a family member needed help? Tell me about that experience.'},
    {'id': 165, 'topic': 'Bundle03', 'type': 'Roleplay_Request', 'question': 'A relative is away for a few days and asked you to cover things at their place—call them and ask what you must know.'},
    {'id': 166, 'topic': 'Bundle03', 'type': 'Roleplay_Problem', 'question': 'You’re at your relative’s place but the spare key isn’t where it should be—call them, explain, and suggest two ways in.'},
    {'id': 167, 'topic': 'Bundle03', 'type': 'Related_Experience', 'question': 'Tell me about a time you promised to help someone but couldn’t follow through.'},
    {'id': 168, 'topic': 'Bundle04', 'type': 'Roleplay_Request', 'question': 'A family member is going on vacation and wants help with a few home tasks—call and ask detailed questions about what to do.'},
    {'id': 169, 'topic': 'Bundle04', 'type': 'Roleplay_Problem', 'question': 'After moving, you spot a broken window—call a repair shop, describe it, and say why you need it fixed soon.'},
    {'id': 170, 'topic': 'Bundle04', 'type': 'Related_Experience', 'question': 'Have you ever agreed to help a friend or family member but later realized you couldn’t? What happened?'},
    {'id': 171, 'topic': 'Bundle05', 'type': 'Roleplay_Request', 'question': "You're thinking about moving—contact a real estate agent, introduce yourself, say what you're looking for, and ask about listings and services."},
    {'id': 172, 'topic': 'Bundle05', 'type': 'Roleplay_Problem', 'question': 'The shop now says the window can’t be fixed until next week—call back and press for an earlier fix with clear reasons.'},
    {'id': 173, 'topic': 'Bundle05', 'type': 'Related_Experience', 'question': 'Have you ever discovered something broken at home unexpectedly? Tell me about it.'},
    {'id': 174, 'topic': 'Bundle06', 'type': 'Roleplay_Request', 'question': 'A home appliance died—at the shop with Ava, ask about features, price, and warranty before you choose a replacement.'},
    {'id': 175, 'topic': 'Bundle06', 'type': 'Roleplay_Problem', 'question': 'A new appliance misbehaves right out of the box—call the store and describe what’s wrong.'},
    {'id': 176, 'topic': 'Bundle06', 'type': 'Related_Experience', 'question': 'Have you ever bought something and later found out there was a problem with it?'},
    {'id': 177, 'topic': 'Bundle07', 'type': 'Roleplay_Request', 'question': 'You and a friend might catch a movie this weekend—call the theater and ask about showtimes, seats, and ticket availability.'},
    {'id': 178, 'topic': 'Bundle07', 'type': 'Roleplay_Problem', 'question': 'At the theater, the tickets don’t match what you bought—tell the agent and offer two ways to sort it out.'},
    {'id': 179, 'topic': 'Bundle07', 'type': 'Related_Experience', 'question': 'Have you ever had trouble with tickets or reservations? Tell me what happened.'},
    {'id': 180, 'topic': 'Bundle08', 'type': 'Roleplay_Request', 'question': "It's your friend's birthday and you want concert tickets—call the ticket office and ask a few questions before you buy."},
    {'id': 181, 'topic': 'Bundle08', 'type': 'Roleplay_Problem', 'question': 'You can’t use the concert tickets anymore—message your friend, explain, and suggest alternatives.'},
    {'id': 182, 'topic': 'Bundle08', 'type': 'Related_Experience', 'question': 'Tell me about a time you missed a concert or performance you really wanted to attend.'},
    {'id': 183, 'topic': 'Bundle09', 'type': 'Roleplay_Request', 'question': 'A friend invited you to the park next weekend—ask where to meet, what to do, and what to bring.'},
    {'id': 184, 'topic': 'Bundle09', 'type': 'Roleplay_Problem', 'question': 'Your weekend park plan is dead because the park is closed—call your friend, explain, and pitch other ideas.'},
    {'id': 185, 'topic': 'Bundle09', 'type': 'Related_Experience', 'question': 'Tell me about a memorable experience you had at a park.'},
    {'id': 186, 'topic': 'Bundle10', 'type': 'Roleplay_Request', 'question': 'You’re planning a weekend beach trip with a friend—call and sort out transport, timing, and what to pack.'},
    {'id': 187, 'topic': 'Bundle10', 'type': 'Roleplay_Problem', 'question': 'A friend wants a ride in an hour but you’re tied up—say why and suggest other meet-up options.'},
    {'id': 188, 'topic': 'Bundle10', 'type': 'Related_Experience', 'question': 'Have you ever had a scary or disappointing experience at the beach?'},
    {'id': 189, 'topic': 'Bundle11', 'type': 'Roleplay_Request', 'question': 'You want seats for an upcoming sports game—ask the seller about seating, pricing, and the schedule.'},
    {'id': 190, 'topic': 'Bundle11', 'type': 'Roleplay_Problem', 'question': 'Beach weather looks awful this weekend—call your friend and suggest another plan.'},
    {'id': 191, 'topic': 'Bundle11', 'type': 'Related_Experience', 'question': 'Tell me about a time you had trouble attending a sports event you really wanted to see.'},
    {'id': 192, 'topic': 'Bundle12', 'type': 'Roleplay_Request', 'question': 'A new café opened nearby—call and ask about the menu, specialties, and how ordering works.'},
    {'id': 193, 'topic': 'Bundle12', 'type': 'Roleplay_Problem', 'question': 'Game tickets are almost gone and the remaining seats aren’t together—leave your friend a voicemail with options.'},
    {'id': 194, 'topic': 'Bundle12', 'type': 'Related_Experience', 'question': 'Tell me about a disappointing experience you had at a coffee shop.'},
    {'id': 195, 'topic': 'Bundle13', 'type': 'Roleplay_Request', 'question': 'Your favorite clothing store is running a huge sale—you hit voicemail. Leave a brief message asking about discounts, items, and hours.'},
    {'id': 196, 'topic': 'Bundle13', 'type': 'Roleplay_Problem', 'question': 'Delivered coffee is the wrong order—call the shop, explain, and suggest two fair fixes.'},
    {'id': 197, 'topic': 'Bundle13', 'type': 'Related_Experience', 'question': 'Describe a memorable shopping experience you’ve had.'},
    {'id': 198, 'topic': 'Bundle14', 'type': 'Roleplay_Request', 'question': 'Friends are coming over to watch something together—contact the rental shop and ask if the movie is available and how rental works.'},
    {'id': 199, 'topic': 'Bundle14', 'type': 'Roleplay_Problem', 'question': 'After a big sale run, one purchase never made it home—call the store and explain what’s missing.'},
    {'id': 200, 'topic': 'Bundle14', 'type': 'Related_Experience', 'question': 'Have you ever wanted to watch a movie or TV show, but something prevented you from doing it?'},
    {'id': 201, 'topic': 'Bundle15', 'type': 'Roleplay_Request', 'question': "You’re buying an MP3 player but feel lost—phone a savvy friend and ask what you'd better know."},
    {'id': 202, 'topic': 'Bundle15', 'type': 'Roleplay_Problem', 'question': 'Movie night at home but the disc won’t play—tell your friends what’s up and suggest quick alternatives.'},
    {'id': 203, 'topic': 'Bundle15', 'type': 'Related_Experience', 'question': 'Tell me about a time when a device or piece of equipment stopped working unexpectedly.'},
    {'id': 204, 'topic': 'Bundle16', 'type': 'Roleplay_Request', 'question': 'You’re curious about vocal lessons—call a music academy and ask about schedules, instructors, and fees.'},
    {'id': 205, 'topic': 'Bundle16', 'type': 'Roleplay_Problem', 'question': 'You borrowed a friend’s music player and broke it—call them, own it, and suggest how to replace it fast.'},
    {'id': 206, 'topic': 'Bundle16', 'type': 'Related_Experience', 'question': 'Tell me about a memorable experience involving singing.'},
    {'id': 207, 'topic': 'Bundle17', 'type': 'Roleplay_Request', 'question': 'You might buy your first instrument—leave a voicemail for the music shop asking about beginner-friendly gear and pricing.'},
    {'id': 208, 'topic': 'Bundle17', 'type': 'Roleplay_Problem', 'question': 'You’ll miss several voice lessons—call the teacher, explain why, and ask about make-ups.'},
    {'id': 209, 'topic': 'Bundle17', 'type': 'Related_Experience', 'question': 'Have you ever had trouble with a musical instrument? What happened?'},
    {'id': 210, 'topic': 'Bundle18', 'type': 'Roleplay_Request', 'question': "You're invited to a dinner party and should bring something—call the host and ask what fits the menu and how many guests to expect."},
    {'id': 211, 'topic': 'Bundle18', 'type': 'Roleplay_Problem', 'question': 'The new instrument has a defect—leave the store a message with the problem and two possible solutions.'},
    {'id': 212, 'topic': 'Bundle18', 'type': 'Related_Experience', 'question': 'Tell me about a memorable experience cooking for someone.'},
    {'id': 213, 'topic': 'Bundle19', 'type': 'Roleplay_Request', 'question': 'A book you’ve been waiting for just dropped—call a bookstore and ask about stock, pricing, or signed editions.'},
    {'id': 214, 'topic': 'Bundle19', 'type': 'Roleplay_Problem', 'question': 'You dropped the dish you were bringing to a party—call your friend, explain, and offer backup ideas.'},
    {'id': 215, 'topic': 'Bundle19', 'type': 'Related_Experience', 'question': 'Tell me about a book that had a strong impact on you.'},
    {'id': 216, 'topic': 'Bundle20', 'type': 'Roleplay_Request', 'question': 'A friend wants you on a walk later—before saying yes, ask about the route, distance, and surface.'},
    {'id': 217, 'topic': 'Bundle20', 'type': 'Roleplay_Problem', 'question': 'The new book has a printing flaw—call the bookstore and describe what’s wrong.'},
    {'id': 218, 'topic': 'Bundle20', 'type': 'Related_Experience', 'question': 'Have you ever gone on a walk and suddenly had to change your route or plans?'},
    {'id': 219, 'topic': 'Bundle21', 'type': 'Roleplay_Request', 'question': 'You need walking-friendly shoes—call a sports store and ask about fit, cushioning, and long-walk picks.'},
    {'id': 220, 'topic': 'Bundle21', 'type': 'Roleplay_Problem', 'question': 'On a walk, your friend wants to keep going but you’re wiped—say so and suggest a shorter loop or a break.'},
    {'id': 221, 'topic': 'Bundle21', 'type': 'Related_Experience', 'question': 'Tell me about a time you returned something because you weren’t satisfied with it.'},
    {'id': 222, 'topic': 'Bundle22', 'type': 'Roleplay_Request', 'question': 'A friend invites you jogging this weekend—ask about the route, meet-up time, and pace.'},
    {'id': 223, 'topic': 'Bundle22', 'type': 'Roleplay_Problem', 'question': 'New walking shoes hurt—return to the store, explain, and ask what they can do.'},
    {'id': 224, 'topic': 'Bundle22', 'type': 'Related_Experience', 'question': 'Tell me about a memorable jogging experience.'},
    {'id': 225, 'topic': 'Bundle23', 'type': 'Roleplay_Request', 'question': 'An old friend is throwing a party—check who’s coming, dress code, and start time.'},
    {'id': 226, 'topic': 'Bundle23', 'type': 'Roleplay_Problem', 'question': 'You can’t make the meet-up you planned—call, explain briefly, and offer other times.'},
    {'id': 227, 'topic': 'Bundle23', 'type': 'Related_Experience', 'question': 'Have you ever had to suddenly change plans with a friend? What happened?'},
    {'id': 228, 'topic': 'Bundle24', 'type': 'Roleplay_Request', 'question': 'You’re planning a short domestic trip—call a travel agent and ask about destinations, transport, and hotels.'},
    {'id': 229, 'topic': 'Bundle24', 'type': 'Roleplay_Problem', 'question': 'You can’t join your friend at the gym today—leave a voicemail and suggest rescheduling.'},
    {'id': 230, 'topic': 'Bundle24', 'type': 'Related_Experience', 'question': 'Tell me about a problem you experienced while planning a vacation.'},
    {'id': 231, 'topic': 'Bundle25', 'type': 'Roleplay_Request', 'question': 'While traveling you hear about a nearby live show—call the ticket desk and confirm details before purchasing.'},
    {'id': 232, 'topic': 'Bundle25', 'type': 'Roleplay_Problem', 'question': 'A non-refundable flight is coming up but you can’t go—call the agency and look for realistic outs.'},
    {'id': 233, 'topic': 'Bundle25', 'type': 'Related_Experience', 'question': 'Have you ever dealt with a canceled flight while traveling?'},
    {'id': 234, 'topic': 'Bundle26', 'type': 'Roleplay_Request', 'question': 'A relative needs backup prepping a big family gathering—call back and ask what’s needed and how you can help.'},
    {'id': 235, 'topic': 'Bundle26', 'type': 'Roleplay_Problem', 'question': 'The package you wanted isn’t available on your dates—tell your friend and brainstorm other trips.'},
    {'id': 236, 'topic': 'Bundle26', 'type': 'Related_Experience', 'question': 'Tell me about a crazy or unforgettable travel experience.'},
    {'id': 237, 'topic': 'Bundle27', 'type': 'Roleplay_Request', 'question': 'You just moved in and recycling rules are fuzzy—call the building manager and ask how sorting and pickup work.'},
    {'id': 238, 'topic': 'Bundle27', 'type': 'Roleplay_Problem', 'question': 'Your flight is canceled and alternatives look full—call the agency and push for workable options.'},
    {'id': 239, 'topic': 'Bundle27', 'type': 'Related_Experience', 'question': 'Have you ever bought tickets for something and then couldn’t go?'},
    {'id': 240, 'topic': 'Bundle28', 'type': 'Roleplay_Request', 'question': 'A friend chose a restaurant you’ve never tried—leave a voicemail asking about location, menu, and vibe.'},
    {'id': 241, 'topic': 'Bundle28', 'type': 'Roleplay_Problem', 'question': 'You can’t rent a car abroad with only your home license—explain the snag and ask for two workarounds.'},
    {'id': 242, 'topic': 'Bundle28', 'type': 'Related_Experience', 'question': 'Tell me about a time you helped a friend or neighbor with a problem.'},
    {'id': 243, 'topic': 'Bundle29', 'type': 'Roleplay_Request', 'question': 'You want a new bank account—at the branch, ask an employee about account types, fees, and perks.'},
    {'id': 244, 'topic': 'Bundle29', 'type': 'Roleplay_Problem', 'question': 'You’re sick on show night—call your friend and suggest what to do with the tickets.'},
    {'id': 245, 'topic': 'Bundle29', 'type': 'Related_Experience', 'question': 'Have you ever had confusion about recycling rules? Tell me what happened.'},
    {'id': 246, 'topic': 'Bundle30', 'type': 'Roleplay_Request', 'question': 'You’re headed overseas and need packing clues—call the hotel and ask about typical weather and what clothes make sense.'},
    {'id': 247, 'topic': 'Bundle30', 'type': 'Roleplay_Problem', 'question': 'You must work on party day—message the relative, explain, and offer remote help with prep.'},
    {'id': 248, 'topic': 'Bundle30', 'type': 'Related_Experience', 'question': 'Tell me about a memorable visit with family or friends.'},
    {'id': 249, 'topic': 'Bundle31', 'type': 'Roleplay_Request', 'question': 'You saw an ad for a new DVD player—call the store and ask what it does and what it costs.'},
    {'id': 250, 'topic': 'Bundle31', 'type': 'Roleplay_Problem', 'question': 'A neighbor keeps sorting trash wrong—call them politely, explain the issue, and suggest easy fixes.'},
    {'id': 251, 'topic': 'Bundle31', 'type': 'Related_Experience', 'question': 'Tell me about an unusual or memorable experience you had at a restaurant.'},
    {'id': 252, 'topic': 'Bundle32', 'type': 'Related_Experience', 'question': 'Tell me about a financial problem you experienced, like losing a card or having banking trouble.'},
    {'id': 253, 'topic': 'Phones', 'type': 'Roleplay_Request', 'question': 'You’re comparing smartphones—ask the salesperson 3–4 tight questions on features, storage, battery, and plans.'},
    {'id': 254, 'topic': 'Internet', 'type': 'Roleplay_Request', 'question': 'A friend mentioned a cool new site—ask what it’s for, how they use it, and why it’s worth it.'},
    {'id': 255, 'topic': 'Country', 'type': 'Roleplay_Request', 'question': 'You need a room for the night in a new city—at the front desk, say what you need and ask about services and availability.'},
    {'id': 256, 'topic': 'Country', 'type': 'Roleplay_Request', 'question': 'You’re at a hotel in a new city and want to explore—ask the desk for nearby sights and food spots.'},
    {'id': 257, 'topic': 'Home', 'type': 'Roleplay_Request', 'question': 'You’re hunting a city apartment—call an agent, describe budget, size, and neighborhood, and ask what’s open.'},
    {'id': 258, 'topic': 'Health', 'type': 'Roleplay_Request', 'question': 'You feel sick and need a doctor—call the clinic, explain symptoms lightly, and ask how to book a visit.'},
    {'id': 259, 'topic': 'Fashion', 'type': 'Roleplay_Request', 'question': 'You need clothes for an event—call a shop and ask about styles, sizes, and what they have in stock.'},
    {'id': 260, 'topic': 'Travel', 'type': 'Roleplay_Request', 'question': 'You need a rental car for a trip—ask the company about price, insurance, and vehicle choices.'},
    {'id': 261, 'topic': 'Health', 'type': 'Roleplay_Request', 'question': 'You want to eat healthier—call a nutritionist and ask how they work and what a first plan might look like.'},
]
